"""Print a read-only staging hygiene report for the current git diff."""

from __future__ import annotations

import argparse
import subprocess
from shlex import quote
from dataclasses import dataclass
from pathlib import Path


SOURCE_PREFIXES = (
    "src/",
    "tests/",
    "scripts/",
    "docs/",
)

ROOT_PRODUCT_FILES = {
    ".gitignore",
    ".streamlit/config.toml",
    "README.md",
    "ROADMAP.md",
    "PRODUCT_SPEC.md",
    "READINESS_MODEL.md",
    "DECISION_OUTPUT_MODEL.md",
    "Makefile",
    "config.yaml",
    "pyproject.toml",
    "data/reviewed_data_proofs.csv",
    "data/reviewed_batch_proofs.csv",
    "outputs/reviewed_batch_packet.csv",
    "outputs/reviewed_batch_packet.md",
}


@dataclass(frozen=True)
class StatusEntry:
    status: str
    path: str


def parse_status_line(line: str) -> StatusEntry:
    if line.startswith("?? "):
        return StatusEntry("??", line[3:])
    return StatusEntry(line[:2].strip(), line[3:])


def parse_name_status_line(line: str) -> StatusEntry:
    parts = line.split("\t")
    status = parts[0].strip()
    path = parts[-1].strip()
    return StatusEntry(status, path)


def is_generated_churn(path: str) -> bool:
    if path.startswith("outputs/stock_reports/") and path.endswith(".md"):
        return False
    if path in {
        "data/reviewed_data_proofs.csv",
        "data/reviewed_batch_proofs.csv",
        "outputs/reviewed_batch_packet.csv",
        "outputs/reviewed_batch_packet.md",
    }:
        return False
    if path.startswith("data/") and path.endswith((".csv", ".json")):
        return True
    if path.startswith("outputs/") and path.endswith((".csv", ".json")):
        return True
    return False


def classify_path(path: str) -> str:
    if is_generated_churn(path):
        return "generated_csv_churn"
    if path.startswith("outputs/stock_reports/") and path.endswith(".md"):
        return "sample_report_candidate"
    if path in ROOT_PRODUCT_FILES or path.startswith(SOURCE_PREFIXES):
        return "product_candidate"
    if path.startswith("stock_analysis/"):
        return "product_candidate"
    return "review_manually"


def load_status(repo_root: Path) -> list[StatusEntry]:
    result = subprocess.run(
        ["git", "status", "--porcelain=v1"],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return [parse_status_line(line) for line in result.stdout.splitlines() if line]


def load_staged_status(repo_root: Path) -> list[StatusEntry]:
    result = subprocess.run(
        ["git", "diff", "--cached", "--name-status"],
        cwd=repo_root,
        check=True,
        capture_output=True,
        text=True,
    )
    return [parse_name_status_line(line) for line in result.stdout.splitlines() if line]


def format_paths(entries: list[StatusEntry], *, limit: int = 80) -> list[str]:
    rows = [f"  {entry.status or 'M'} {entry.path}" for entry in entries[:limit]]
    if len(entries) > limit:
        rows.append(f"  ... {len(entries) - limit} more")
    return rows


def format_git_add_command(entries: list[StatusEntry], *, label: str, max_paths: int = 80) -> list[str]:
    if not entries:
        return [f"  # {label}: no files in this bucket"]
    paths = [entry.path for entry in entries[:max_paths]]
    command = "git add -- " + " ".join(quote(path) for path in paths)
    rows = [f"  # {label}", f"  {command}"]
    if len(entries) > max_paths:
        rows.append(f"  # Review and stage {len(entries) - max_paths} additional file(s) from this bucket manually.")
    return rows


def write_path_file(path: Path, entries: list[StatusEntry]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "".join(f"{entry.path}\n" for entry in entries)
    path.write_text(body, encoding="utf-8")


def count_path_file(path: Path) -> int:
    text = path.read_text(encoding="utf-8") if path.exists() else ""
    return len([line for line in text.splitlines() if line.strip()])


def build_staging_readme(files: dict[str, Path], repo_root: Path) -> str:
    def _rel(path: Path) -> str:
        return path.relative_to(repo_root).as_posix()

    def _line(label: str, key: str) -> str:
        path = files[key]
        return f"- {label}: {_rel(path)} ({count_path_file(path)} path(s))"

    return "\n".join(
        [
            "Diff Hygiene Local Staging Files",
            "",
            "These ignored files are generated by `make diff-hygiene-files`.",
            "They are review aids only; the command does not stage, delete, reset, refresh, or rewrite product data.",
            "",
            _line("Product files", "product_files"),
            _line("Product plus reviewed Markdown reports", "product_plus_reports"),
            _line("Markdown sample reports only", "sample_reports"),
            _line("Generated CSV/JSON churn to avoid by default", "generated_churn"),
            _line("Manual-review paths", "manual_review"),
            "",
            "After reviewing the path list you want, optional staging commands are:",
            "git add --pathspec-from-file=outputs/staging/product_files.txt",
            "git add --pathspec-from-file=outputs/staging/product_plus_reports.txt",
            "make staged-hygiene-check",
            "",
            "Do not stage generated churn by default. It is listed separately so it can be inspected, not swept into public commits.",
            "Research-only guardrail: never stage broker, order execution, auto-trading, options recommendation, or direct buy/sell instruction language.",
            "",
        ]
    )


def write_staging_files(entries: list[StatusEntry], output_dir: Path) -> dict[str, Path]:
    groups = group_entries(entries)
    files = {
        "readme": output_dir / "README.txt",
        "product_files": output_dir / "product_files.txt",
        "product_plus_reports": output_dir / "product_plus_reports.txt",
        "sample_reports": output_dir / "sample_reports.txt",
        "generated_churn": output_dir / "generated_churn.txt",
        "manual_review": output_dir / "manual_review.txt",
    }
    write_path_file(files["product_files"], groups["product_candidate"])
    write_path_file(files["product_plus_reports"], groups["product_candidate"] + groups["sample_report_candidate"])
    write_path_file(files["sample_reports"], groups["sample_report_candidate"])
    write_path_file(files["generated_churn"], groups["generated_csv_churn"])
    write_path_file(files["manual_review"], groups["review_manually"])
    files["readme"].write_text(build_staging_readme(files, output_dir.parents[1]), encoding="utf-8")
    return files


def build_file_report(files: dict[str, Path], repo_root: Path) -> str:
    def _rel(path: Path) -> str:
        return path.relative_to(repo_root).as_posix()

    def _file_line(label: str, key: str) -> str:
        path = files[key]
        return f"{label}: {_rel(path)} ({count_path_file(path)} path(s))"

    product_file = _rel(files["product_files"])
    product_plus_reports_file = _rel(files["product_plus_reports"])
    generated_file = _rel(files["generated_churn"])
    return "\n".join(
        [
            "Diff Hygiene File Lists",
            "Generated local path lists for review; this did not stage, delete, reset, refresh, or rewrite product data.",
            "",
            _file_line("Product files", "product_files"),
            _file_line("Product plus reviewed Markdown reports", "product_plus_reports"),
            _file_line("Markdown sample reports only", "sample_reports"),
            _file_line("Generated CSV/JSON churn to avoid by default", "generated_churn"),
            _file_line("Manual-review paths", "manual_review"),
            f"Usage notes: {_rel(files['readme'])}",
            "",
            "Optional staging commands after review:",
            f"  git add --pathspec-from-file={product_file}",
            f"  git add --pathspec-from-file={product_plus_reports_file}",
            "  make staged-hygiene-check",
            "",
            "Do not stage generated churn by default. Review this file instead:",
            f"  {generated_file}",
            "",
            "Research-only guardrail: never stage broker, order execution, auto-trading,",
            "options recommendation, or direct buy/sell instruction language.",
        ]
    )


def count_new(entries: list[StatusEntry]) -> int:
    return sum(1 for entry in entries if entry.status in {"??", "A"})


def format_count_line(label: str, entries: list[StatusEntry]) -> str:
    new_count = count_new(entries)
    changed_count = len(entries) - new_count
    return f"{label}: {len(entries)} ({changed_count} changed, {new_count} new)"


def group_entries(entries: list[StatusEntry]) -> dict[str, list[StatusEntry]]:
    groups: dict[str, list[StatusEntry]] = {
        "product_candidate": [],
        "sample_report_candidate": [],
        "generated_csv_churn": [],
        "review_manually": [],
    }
    for entry in entries:
        groups[classify_path(entry.path)].append(entry)
    return groups


def build_summary_report(entries: list[StatusEntry]) -> str:
    groups = group_entries(entries)
    lines = [
        "Diff Hygiene Summary",
        "Read-only: this command does not stage, delete, reset, refresh, or rewrite files.",
        "",
    ]
    if not entries:
        lines.append("Working tree is clean.")
        return "\n".join(lines)
    lines.extend(
        [
            format_count_line("Product/code/docs/test candidates", groups["product_candidate"]),
            format_count_line("Markdown sample report candidates", groups["sample_report_candidate"]),
            format_count_line("Generated CSV/JSON churn to avoid by default", groups["generated_csv_churn"]),
            format_count_line("Manual-review paths", groups["review_manually"]),
            "",
            "Use `make diff-hygiene` for full file lists and safe staging suggestions.",
            "New docs/scripts/tests are product candidates when intentional; review them before staging.",
            "Generated CSV/JSON churn is intentionally excluded from the suggested staging commands.",
            "",
            "Research-only guardrail: never stage broker, order execution, auto-trading,",
            "options recommendation, or direct buy/sell instruction language.",
        ]
    )
    return "\n".join(lines)


def staged_hygiene_has_blockers(entries: list[StatusEntry]) -> bool:
    groups = group_entries(entries)
    return bool(groups["generated_csv_churn"] or groups["review_manually"])


def tracked_entries(entries: list[StatusEntry]) -> list[StatusEntry]:
    return [entry for entry in entries if entry.status != "??"]


def untracked_entries(entries: list[StatusEntry]) -> list[StatusEntry]:
    return [entry for entry in entries if entry.status == "??"]


def format_shell_command(
    prefix: str,
    entries: list[StatusEntry],
    *,
    max_paths: int = 60,
    empty_message: str = "# no matching paths",
) -> list[str]:
    if not entries:
        return [f"  {empty_message}"]
    paths = " ".join(quote(entry.path) for entry in entries[:max_paths])
    rows = [f"  {prefix} {paths}"]
    if len(entries) > max_paths:
        rows.append(f"  # Review {len(entries) - max_paths} additional path(s) manually before extending this command.")
    return rows


def build_data_release_decision_report(entries: list[StatusEntry]) -> str:
    groups = group_entries(entries)
    product = groups["product_candidate"]
    generated = groups["generated_csv_churn"]
    manual = groups["review_manually"]
    sample_reports = groups["sample_report_candidate"]
    proof_artifacts = [
        entry
        for entry in product
        if entry.path
        in {
            "data/reviewed_data_proofs.csv",
            "data/reviewed_batch_proofs.csv",
            "outputs/reviewed_batch_packet.csv",
            "outputs/reviewed_batch_packet.md",
        }
    ]
    product_without_proofs = [entry for entry in product if entry not in proof_artifacts]
    cleanup_tracked = tracked_entries(generated + proof_artifacts)
    cleanup_untracked = untracked_entries(generated + proof_artifacts)

    lines = [
        "Data Release Decision",
        "Read-only: this command does not stage, delete, reset, refresh, rewrite files, or publish data.",
        "Research-only: data release choices are evidence-packaging decisions, not investment advice or execution instructions.",
        "",
    ]
    if not entries:
        lines.extend(
            [
                "Working tree is clean.",
                "Recommendation: public code/docs/tests are ready to share; no local data release package is pending.",
                "",
                "Next safe data step:",
                "  make coverage-expansion-loop TOP_N=10",
            ]
        )
        return "\n".join(lines)

    lines.extend(
        [
            format_count_line("Product/code/docs/test candidates", product_without_proofs),
            format_count_line("Reviewed proof artifacts", proof_artifacts),
            format_count_line("Generated CSV/JSON churn", generated),
            format_count_line("Markdown sample report candidates", sample_reports),
            format_count_line("Manual-review paths", manual),
            "",
        ]
    )

    if manual:
        lines.extend(
            [
                "Stop first: manual-review paths are present.",
                "Inspect these before choosing a public-code cleanup or reviewed data release:",
                *format_paths(manual, limit=30),
                "",
            ]
        )

    lines.extend(
        [
            "Recommended decision:",
        ]
    )
    if generated:
        lines.append(
            "  Keep generated CSV/JSON churn local by default. Publish a data snapshot only when the exact refreshed artifacts are the deliverable."
        )
    elif proof_artifacts:
        lines.append(
            "  Proof ledger artifacts changed without generated churn; stage them only if they describe an intentionally reviewed outcome."
        )
    elif product_without_proofs or sample_reports:
        lines.append("  Stage product/docs/tests or reviewed Markdown samples with the normal diff-hygiene path.")
    else:
        lines.append("  No generated data release decision is pending.")

    lines.extend(
        [
            "",
            "Option A - public code/docs release",
            "Use when refreshed data was only local working evidence and should not become the public snapshot.",
            "Copy only after confirming the local batch evidence can be discarded:",
        ]
    )
    lines.extend(format_shell_command("git restore --", cleanup_tracked, empty_message="# no tracked generated/proof paths to restore"))
    lines.extend(format_shell_command("rm -f", cleanup_untracked, empty_message="# no untracked generated/proof paths to remove"))
    lines.extend(
        [
            "  make diff-hygiene-summary",
            "",
            "Option B - reviewed data snapshot release",
            "Use only when the refreshed CSVs and proof artifacts are intentionally part of the deliverable.",
        ]
    )
    if proof_artifacts:
        lines.extend(format_git_add_command(proof_artifacts, label="Stage reviewed proof artifacts"))
    else:
        lines.append("  # No reviewed proof artifact changed; record or review the proof row before publishing data churn.")
    if generated:
        lines.extend(
            [
                "  # Review generated churn individually; do not use git add -A.",
                "  make diff-hygiene-files",
                "  # Inspect outputs/staging/generated_churn.txt, then stage only the exact reviewed artifacts.",
            ]
        )
    else:
        lines.append("  # No generated CSV/JSON churn is present.")
    lines.extend(
        [
            "  make staged-hygiene-check",
            "  make public-check",
            "",
            "Option C - keep local evidence only",
            "Use when the batch result matters locally but should not be committed yet.",
            "  # Do nothing to git; keep the dirty tree local and rerun make diff-hygiene before any commit.",
            "",
            "Do not proceed if:",
            "- source proof is unavailable",
            "- validation, preview, rejected-row review, or apply decision is missing for a mutating workflow",
            "- changed readiness counts or changed tickers are not documented",
            "- generated artifacts cannot be classified before staging",
            "",
            "Research-only guardrail: never stage broker, order execution, auto-trading,",
            "options recommendation, or direct buy/sell instruction language.",
        ]
    )
    return "\n".join(lines)


def build_staged_check_report(entries: list[StatusEntry]) -> str:
    groups = group_entries(entries)
    lines = [
        "Staged Hygiene Check",
        "Read-only: this command inspects the staged diff and does not stage, delete, reset, refresh, or rewrite files.",
        "",
    ]
    if not entries:
        lines.append("No staged changes. Nothing to commit yet.")
        return "\n".join(lines)

    lines.extend(
        [
            format_count_line("Staged product/code/docs/test files", groups["product_candidate"]),
            format_count_line("Staged Markdown sample reports", groups["sample_report_candidate"]),
            format_count_line("Staged generated CSV/JSON churn", groups["generated_csv_churn"]),
            format_count_line("Staged manual-review paths", groups["review_manually"]),
            "",
        ]
    )
    if staged_hygiene_has_blockers(entries):
        lines.extend(
            [
                "Staged hygiene check failed.",
                "Generated CSV/JSON churn or manual-review paths are staged. Unstage or explicitly review them before committing.",
            ]
        )
        if groups["generated_csv_churn"]:
            lines.extend(["", "Generated CSV/JSON churn currently staged:"])
            lines.extend(format_paths(groups["generated_csv_churn"], limit=40))
        if groups["review_manually"]:
            lines.extend(["", "Manual-review paths currently staged:"])
            lines.extend(format_paths(groups["review_manually"], limit=40))
    else:
        lines.extend(
            [
                "Staged hygiene check passed.",
                "Only product/code/docs/tests and reviewed Markdown sample reports are staged.",
            ]
        )
    lines.extend(
        [
            "",
            "Research-only guardrail: never stage broker, order execution, auto-trading,",
            "options recommendation, or direct buy/sell instruction language.",
        ]
    )
    return "\n".join(lines)


def build_report(entries: list[StatusEntry]) -> str:
    groups = group_entries(entries)
    lines = [
        "Diff Hygiene Report",
        "Read-only: this command does not stage, delete, reset, refresh, or rewrite files.",
        "",
    ]
    if not entries:
        lines.append("Working tree is clean.")
        return "\n".join(lines)

    sections = (
        (
            "Likely product/code/docs/test candidates",
            groups["product_candidate"],
            "Review normally. New docs/scripts/tests in this bucket can be staged when intentional.",
        ),
        (
            "Small Markdown sample report candidates",
            groups["sample_report_candidate"],
            "Stage only if the regenerated examples demonstrate intentional visitor-facing behavior.",
        ),
        (
            "Generated CSV/JSON churn",
            groups["generated_csv_churn"],
            "Do not stage by default. Keep only if the data artifact itself is the deliverable.",
        ),
        (
            "Manual review required",
            groups["review_manually"],
            "Inspect these paths before deciding whether they belong in the public diff.",
        ),
    )
    for title, section_entries, note in sections:
        lines.extend([title, note, format_count_line("Count", section_entries)])
        lines.extend(format_paths(section_entries) if section_entries else ["  none"])
        lines.append("")

    lines.extend(
        [
            "Safe staging suggestions:",
            "These commands intentionally exclude generated CSV/JSON churn.",
            "They include new product docs/scripts/tests because those are commonly intentional in public polish work.",
            *format_git_add_command(groups["product_candidate"], label="Stage product/code/docs/tests only"),
            *format_git_add_command(
                groups["product_candidate"] + groups["sample_report_candidate"],
                label="Stage product files plus reviewed Markdown sample reports",
            ),
            "",
            "Verification commands:",
            "  git diff --stat",
            "  git diff --check",
            "  make staged-hygiene-check",
            "  git diff --cached --stat",
            "  git diff --cached --name-only",
            "",
            "Research-only guardrail: never stage broker, order execution, auto-trading,",
            "options recommendation, or direct buy/sell instruction language.",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Print a read-only git diff hygiene report.")
    parser.add_argument("--summary", action="store_true", help="Print counts and guidance without long file lists.")
    parser.add_argument(
        "--write-files",
        action="store_true",
        help="Write newline-delimited staging candidate path lists under outputs/staging.",
    )
    parser.add_argument(
        "--staged-check",
        action="store_true",
        help="Fail if the staged diff includes generated CSV/JSON churn or manual-review paths.",
    )
    parser.add_argument(
        "--data-release-decision",
        action="store_true",
        help="Print read-only keep-local vs reviewed-data-release vs cleanup guidance for dirty generated artifacts.",
    )
    args = parser.parse_args()
    repo_root = Path(__file__).resolve().parents[1]
    if args.staged_check:
        entries = load_staged_status(repo_root)
        print(build_staged_check_report(entries))
        return 1 if staged_hygiene_has_blockers(entries) else 0
    entries = load_status(repo_root)
    if args.data_release_decision:
        print(build_data_release_decision_report(entries))
        return 0
    if args.write_files:
        files = write_staging_files(entries, repo_root / "outputs" / "staging")
        print(build_file_report(files, repo_root))
    else:
        print(build_summary_report(entries) if args.summary else build_report(entries))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
